name: igmpproxy

on:
  push:
    paths:
    - igmpproxy/**
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - id: version
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        export VERSION=$(curl https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz | tar -Oxz | grep -FaxA1 "P:igmpproxy" | tail -n1 | cut -d: -f2)
        docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/igmpproxy:${VERSION} > /dev/null && echo "" || echo "::set-output name=version::${VERSION}"
  publish:
    needs: update
    if: ${{ needs.update.outputs.version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        build-args: |
          VERSION=${{ needs.update.outputs.version }}
        context: igmpproxy
        file: igmpproxy/Dockerfile
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/igmpproxy
          ${{ secrets.DOCKERHUB_USERNAME }}/igmpproxy:${{ needs.update.outputs.version }}
